name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código-fonte
    - name: Checkout code
      uses: actions/checkout@v3

    # Configuração do .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    # Login no Azure com as credenciais configuradas
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Restauração de dependências do projeto .NET
    - name: Restore dependencies
      run: dotnet restore

    # Compilação do projeto .NET
    - name: Build
      run: dotnet build --no-restore

    # Publicação do projeto para gerar artefatos
    - name: Publish
      run: dotnet publish -c Release -o ./published

    # Implantação no Azure App Service
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'SustainableEnergyAPI'
        slot-name: 'production'
        package: ./published
